### ISSUE TITLE
Compile Qt5 with proprietary codecs

### ISSUE THREAD

**Issue by Biodiscus** [koendv/qt5-opengl-raspberrypi#2]
I'm compiling this project with proprietary codecs right now, is it okay with you if I will add the instructions to this document as well?

**Comment by koendv** [comment]
On Mon, 01 Jun 2020 07:33:20 -0700
Biodiscus <notifications@github.com> wrote:

> I'm compiling this project with proprietary codecs right now, is it
> okay with you if I will add the instructions to this document as well?
> 

OK. The reason why I have not touched the subject of proprietary
codecs is that I have not enough knowledge about the legal status. 
AFAIK, instructions are fine, binaries are not. 

How about this: if you put up a page on your github that is technically
correct and legally clean I'll link to it?

I would suggest add some explanation:

If you display a page with qtwebengine ...

- the following video and audio formats will always work, because they
  are non-proprietary codecs that are always compiled in : ...

- web pages with proprietary codecs (mpeg4, ... ) will fail, unless you
  compile qt with proprietary codecs ...

- qt compiled with proprietary codecs cannot be freely distributed
  because ...

- solutions:
  - convert videos to free/libre format. good solution for e.g.
    street kiosks. 
	example of conversion command
  - compile qt with proprietary codecs yourself, 
    	example of configure command
  - pay licence fees
	example: mpeg4 licencing authority


regards,

koen

**Comment by Biodiscus** [comment]
Hi,

Souds like a great plan :). And I'll look more into it, but I think instructions on how to do it should be fine. It's only one option when configuring and a SED. When I can validate everything is running nicely, I'll write a page for it :)

**Comment by koendv** [comment]
On Mon, 01 Jun 2020 12:01:30 -0700
Biodiscus <notifications@github.com> wrote:

> Hi,
> 
> Souds like a great plan :). And I'll look more into it, but I think
> instructions on how to do it should be fine. It's only one option
> when configuring and a SED. When I can validate everything is running
> nicely, I'll write a page for it :)
> 

If you look in the Qt sources for USE_PROPRIETARY_CODECS, you find two
files: content_client_qt.cpp and content_renderer_client_qt.cpp .
Take a look at what codecs are always available.

koen
